services:
  client:
    image: nginx:alpine

    container_name: nexuscm-client

    restart: unless-stopped

    volumes:
      - ../../clients/cinny/dist:/usr/share/nginx/html:ro

    expose:
      - "80"

    networks:
      - frontend

    security_opt:
      - no-new-privileges:true
