services:
  postgres:
    image: postgres:17-alpine
    container_name: nexuscm-postgres

    restart: unless-stopped

    env_file:
      - ../env/postgres.env

    environment:
      POSTGRES_DB: synapse
      POSTGRES_USER: synapse

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    networks:
      - backend

    security_opt:
      - no-new-privileges:true

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
